### ISSUE TITLE
anomaly_lof

### ISSUE THREAD

**Issue by erblast** [IMPALA-Consortium/ctasval#3]
Follow design of:
https://impala-consortium.github.io/ctasval/reference/anomaly.html

**Comment by fcollinbi** [comment]
Introduction of lof specific noise could be done by applying principal components to timeseries. Alter the first (most important) 1-5 components (I suggest starting out changing only 2 as those can be easily visualized in an 2d plot) and transform back. The noise could be something like adding y% of there average principal component value. Transformation is possible both ways as it is linear.

**Comment by erblast** [comment]
solved it now by sampling new data based on a random non-normal distribution for a percentage of patients determined by anomaly_degree
